blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/VPremiss/Arabicable/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/VPremiss/Arabicable/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/VPremiss/Arabicable/security/policy
    about: Here is how to notify us about critical security holes
